// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGDFn3e5YVye3l0Kt0jkGbWn4q9BOF3ro',
    appId: '1:15470352707:web:ec3a66117608633146f7f6',
    messagingSenderId: '15470352707',
    projectId: 'ppb-course',
    authDomain: 'ppb-course.firebaseapp.com',
    storageBucket: 'ppb-course.firebasestorage.app',
    measurementId: 'G-RV5X1GMWRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1mkNk0CpCTethEi8y-usr2f1bFHXtMGg',
    appId: '1:15470352707:android:1cb2a26e3056dff146f7f6',
    messagingSenderId: '15470352707',
    projectId: 'ppb-course',
    storageBucket: 'ppb-course.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxW0AMjOzHerlAH7bS5kL7G-P0DGMOQ1A',
    appId: '1:15470352707:ios:a1da946df92256ad46f7f6',
    messagingSenderId: '15470352707',
    projectId: 'ppb-course',
    storageBucket: 'ppb-course.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxW0AMjOzHerlAH7bS5kL7G-P0DGMOQ1A',
    appId: '1:15470352707:ios:a1da946df92256ad46f7f6',
    messagingSenderId: '15470352707',
    projectId: 'ppb-course',
    storageBucket: 'ppb-course.firebasestorage.app',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGDFn3e5YVye3l0Kt0jkGbWn4q9BOF3ro',
    appId: '1:15470352707:web:082467922d236fe646f7f6',
    messagingSenderId: '15470352707',
    projectId: 'ppb-course',
    authDomain: 'ppb-course.firebaseapp.com',
    storageBucket: 'ppb-course.firebasestorage.app',
    measurementId: 'G-8JL83E5EJ0',
  );


}
